name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release Name'
        required: true

jobs:
  build_and_release:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Set Short SHA
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.Substring(0,7))" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set Release Name from Input
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_NAME=${{ github.event.inputs.release_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set Release Name for Push Trigger
        if: github.event_name == 'push'
        run: echo "RELEASE_NAME=$env:SHORT_SHA" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Cache node_modules cache
        id: cache-node
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build native .node modules
        run: yarn cmake

      - name: Compile typescript nestjs project
        run: yarn nest

      - name: Bundle everything to a single file
        run: yarn esbuild

      - name: Create a windows executable
        run: yarn native

      - name: Create GitHub Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $env:RELEASE_NAME `
            ./dist/stream-alert.exe#app.exe `
            --title $env:RELEASE_NAME `
            --notes "Release $env:RELEASE_NAME"

