name: release

on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies # TODO cache
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libv4l-dev

      - uses: actions/setup-node@v6
        with:
          package-manager-cache: false
          node-version: 24
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build native .node modules
        run: yarn cmake

      - name: Compile typescript nestjs project
        run: yarn nest

      - name: Bundle everything to a single file
        run: yarn esbuild

      - name: Create a windows executable
        run: yarn native

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/stream-alert.exe
          asset_name: stream-alert.elf
          asset_content_type: application/x-executable

  win32:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build native .node modules
        run: yarn cmake

      - name: Compile typescript nestjs project
        run: yarn nest

      - name: Bundle everything to a single file
        run: yarn esbuild

      - name: Create a windows executable
        run: yarn native

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/stream-alert.exe
          asset_name: stream-alert.exe
          asset_content_type: application/vnd.microsoft.portable-executable

  aur:
    needs: [linux]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy PKGBUILD and related files
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=$(jq -r '.version' package.json)
          sed -i "s/^pkgver=.*/pkgver=${VERSION}/" ./packages/arch/PKGBUILD
          sed -i "s/^tag=.*/tag=${TAG}/" ./packages/arch/PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: stream-alert
          pkgbuild: ./packages/arch/PKGBUILD
          assets: |
            ./packages/arch/stream-alert.install
            ./packages/stream-alert.service
          commit_username: "GitHub Actions Bot"
          updpkgsums: "true"
          commit_email: "actions@github.com"
          ssh_private_key: ${{ secrets.PK_ARCH }}

  deb:
    runs-on: ubuntu-22.04
    needs: [linux]
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Prepare package
        env:
          DEBEMAIL: "deathangel908@gmail.com"
          DEBFULLNAME: "Andrew Koidan"
        run: |
          url="https://github.com/akoidan/stream-alert"
          tag="${{ github.event.release.tag_name }}"
          wget -q "${url}/releases/download/${tag}/stream-alert.elf"
          VERSION=$(jq -r '.version' ./package.json)
          rootdir=$(pwd)
          srcdir="${rootdir}/packages/debian"
          pkgdir="${srcdir}/stream-alert"
          sed -i "s/^Version:.*/Version: ${VERSION}/" "${srcdir}/control"
          install -D -m 644 "${srcdir}/control" "${pkgdir}/DEBIAN/control"
          install -D -m 755 "${rootdir}/stream-alert.elf" "${pkgdir}/usr/bin/stream-alert"
          install -D -m 644 "${rootdir}/packages/stream-alert.service" "${pkgdir}/usr/lib/systemd/user/stream-alert.service"
          cd "$srcdir"
          dpkg-deb --build stream-alert stream-alert-amd64.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: packages/debian/stream-alert-amd64.deb
          asset_name: stream-alert.deb
          asset_content_type: application/vnd.debian.binary-package
